@startuml employee-management
title Employee management

participant Business owner
participant Client
participant Server

Business owner -> Client: Selects "Edit employees" functionality
activate Client
Client -> Server: Get current employees
activate Server
Server --> Client: Returns current employees
deactivate Server
Client --> Business owner: Shows current employees
deactivate Client



opt
Business owner -> Client: Chooses to add a new employee
activate Client
Client --> Business owner: New employee object created
Business owner -> Client: Input employee info
Client -> Server: Insert new employee record with status=1
activate Server
Server --> Client: Success
deactivate Server
Client --> Business owner: Success
deactivate Client
end

opt 
Business owner -> Client: Selects "Edit employee"
activate Client
Client -> Server: Insert a new version of the employee record with updated fields and a newer timestamp
activate Server
Server --> Client: Success
deactivate Server
Client --> Business owner: Success
deactivate Client
end

opt 
Business owner -> Client: Selects "Fire employee"
activate Client
Client -> Server: Insert new employee record with status=0
activate Server
Server --> Client: Success
deactivate Server
Client --> Business owner: Success
deactivate Client
end
@enduml employee-management
