@startumltitle Menu managementManager->Client: Open item menuactivate ClientClient->Server: Retreive itemsactivate ServerClient<--Server:Items retreiveddeactivate ServerManager<--Client: Show item menudeactivate Clientalt adding an itemManager->Client: Create new itemactivate ClientClient->Server: Upload new itemactivate ServerClient<--Server: New item uploadeddeactivate ServerManager<--Client: New item  addeddeactivate Clientelse edit or remove an itemManager->Client: Select itemactivate ClientManager<--Client: Display itemalt item removalManager->Client: Remove itemClient->Server: Update item status to deletedactivate ServerClient<--Server:Item status updateddeactivate ServerManager<--Client: Item removedelse item editingManager->Client: Modify itemClient->Server: Upload updated item dataactivate ServerClient<--Server: Updated item data uploadeddeactivate ServerManager<--Client: Item modifieddeactivate Clientendend@enduml