title Payment System
opt Add tip
	Operator->Client: Add tip amount
	Client-->Operator: Show new total sum
end
loop Until total sum is paid
  Operator->Client: Select payment method, amount
  alt Cash Payment
    Client->Server: Upload cash payment info
    Server-->Client: Confirm cash payment
    Client-->Operator: Show remaining balance
  else Card Payment
    
    Client->Stripe: Create payment intent
    alt Payment Authorized
      Stripe-->Client: Payment authorized
      Client-->Operator: Show remaining balance
    else Payment Declined
      Stripe-->Client: Payment declined
      Client-->Operator: Show error, retry
    end
  else GiftCard Payment
    Client->Server: Upload giftcard payment info
    Server->Server: Reduce gift card remaining balance
    alt Payment Accepted
      Server-->Client: Confirm giftcard payment
      Client-->Operator: Show remaining balance
    else Insufficient Balance
      Server-->Client: Decline payment
      Client-->Operator: Show error, retry
    end
  end
end

Operator->Client: Close order
Client->Server: Upload closed order
Server->Server: Generate receipt
Server-->Client: Order closed
Client-->Operator: Provide receipt
